[tool.pyright]
pythonVersion = "3.12"
venvPath = "/Users/huvinesh/miniconda/envs"
venv = "/Users/huvinesh/miniconda/envs/keras"
strictListInference = true
strictDictionaryInference = true
strictSetInference = true
